Feat: Add OpenAI and Azure voice services
joethei/obsidian-tts pull request #39
Opened 2024-09-28 04:29 UTC by pyarmak

I have taken the liberty of implementing two additional AI voice services, namely, OpenAI (which you basically had already finished) and Azure.
It's been tested to work but it's a quick and dirty addition so may need some polish.

2024-09-30 08:51 UTC, joethei requested changes

2024-09-30 08:51 UTC, joethei commented on src/ServiceConfigurationModal.ts
> +				.setName('Speech Region')
Use sentence case

2024-09-30 08:51 UTC, joethei commented on src/ServiceConfigurationModal.ts
> +				.setName('API Key')
Use sentence case

2024-09-30 08:51 UTC, joethei commented on src/settings.ts
> +		const servicesEl = containerEl.createDiv("settings-banner", (banner) => {
Use `new Setting(containerEl).setName('Configured services').setHeading();` instead.

2024-10-01 18:53 UTC, pyarmak commented
I'm actually working on a couple of more features. I went down a rabbit hole.
I will update my code with your suggestions and will update the PR once I have completed the other features.
Namely, I'm adding a custom regex filter for the input text (I'll add it under advanced features in the settings) and the ability to play/pause/stop/seek the generated audio output. To that end, I am modifying the createMenu function and completely removing the menu and instead dynamically adding buttons and the seek bar to the status bar.

2024-10-01 19:35 UTC, joethei commented
Could you put those features in a separate PR?

2024-10-05 08:50 UTC, closed without merging